package EX9_06;
//TWORZE INTERFEJS PACKABLE Z JEDNA METODA KTORA BEDZIE
// NADPISYWANA W KAZDEJ KLASIE W KTOREJ INTERFEJS ZOSTANIE
// ZAIMPLEMENTOWANY
public interface Packable {

    double weight ();

}
