package ex9_03;
//KLASA TRORA DZIEDZICZY PO KLASIE PRODUCTWAREHOUSE
//TA KLASA BEDZIE MAGAZYNEM PRODUKTOW ALE Z HISTORIA, BEDZIE UZYWALA
//KLASY CHANGEHISTORY
public class ProductWarehouseWithHistory extends ProductWarehouse{

}
